### ISSUE TITLE
비즈니스 로직 구현하기

### ISSUE THREAD

**Issue by dnya0** [NadudAn/OwnPli_BackEnd#7]
- [x] 로그인 기능 구현하기(https://github.com/NadudAn/OwnPli_BackEnd/issues/11)
- [x] 레포지토리 생성 및 구현하기(https://github.com/NadudAn/OwnPli_BackEnd/issues/6)
- [x] 서비스 생성 및 구현하기(https://github.com/NadudAn/OwnPli_BackEnd/issues/8)
- [x] 서버단 Mp3파일 클라이언트로 보내기(https://github.com/NadudAn/OwnPli_BackEnd/issues/12)
- [x] 이미지 파일 전송하기(https://github.com/NadudAn/OwnPli_BackEnd/issues/13)
- [x] top100, 연령별 추천, 맞춤 추천 리스트 보내기 (https://github.com/NadudAn/OwnPli_BackEnd/issues/14)
- [x] 연관관계 수정하기(https://github.com/NadudAn/OwnPli_BackEnd/issues/15)
- [x] DTO 생성하기(https://github.com/NadudAn/OwnPli_BackEnd/issues/17)
